# numpy的运算

In [2]:
import numpy as np
array1=np.arange(1,6)

## 单个向量的运算

### 加减运算

In [3]:
print(array1)
print("array1+5:",array1+5)
print("array1-5:",array1-5)
print("array1*5:",array1*5)
print("array1/5:",array1/5)

[1 2 3 4 5]
array1+5: [ 6  7  8  9 10]
array1-5: [-4 -3 -2 -1  0]
array1*5: [ 5 10 15 20 25]
array1/5: [0.2 0.4 0.6 0.8 1. ]


### 绝对值,三角函数运算

In [4]:
arr=np.random.normal(0,10,size=(3,2))
arr1=np.linspace(0,np.pi,3)
x=[1,0,-1]
print("绝对值",abs(arr))
print("绝对值",np.abs(arr))
print("sin(arr1):",np.sin(arr1))
print("cos(arr1):",np.cos(arr1))
print("tan(arr1):",np.tan(arr1))
print("arcsin(arr1):",np.arcsin(x))
print("arccos(arr1):",np.arccos(x))
print("arctan(arr1):",np.arctan(x))

绝对值 [[ 2.77569234 13.02203015]
 [ 9.37791524  8.59198767]
 [13.13547965  9.67365861]]
绝对值 [[ 2.77569234 13.02203015]
 [ 9.37791524  8.59198767]
 [13.13547965  9.67365861]]
sin(arr1): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(arr1): [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(arr1): [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(arr1): [ 1.57079633  0.         -1.57079633]
arccos(arr1): [0.         1.57079633 3.14159265]
arctan(arr1): [ 0.78539816  0.         -0.78539816]


### 指数,对数运算

In [5]:
print(np.exp(array1))
print("ln(x):",np.log(array1))
print("log2(x)",np.log2(array1))
print("log10(10),",np.log10(array1))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
ln(x): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log2(x) [0.         1.         1.5849625  2.         2.32192809]
log10(10), [0.         0.30103    0.47712125 0.60205999 0.69897   ]


## 矩阵的运算

In [6]:
array2=np.arange(9).reshape(3,3)
array3=np.full((3,3),7)
print("a2:",array2)
print("a3:",array3)
print("a2+a3:",array2+array3)
print("a2-a3:",array2-array3)
print("a2*a3:",array2*array3)
print("a2/a3:",array2/array3)

a2: [[0 1 2]
 [3 4 5]
 [6 7 8]]
a3: [[7 7 7]
 [7 7 7]
 [7 7 7]]
a2+a3: [[ 7  8  9]
 [10 11 12]
 [13 14 15]]
a2-a3: [[-7 -6 -5]
 [-4 -3 -2]
 [-1  0  1]]
a2*a3: [[ 0  7 14]
 [21 28 35]
 [42 49 56]]
a2/a3: [[0.         0.14285714 0.28571429]
 [0.42857143 0.57142857 0.71428571]
 [0.85714286 1.         1.14285714]]


### 矩阵的转置

In [7]:
print(array2)
print(array2.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


## 矩阵的逆

In [8]:
A=np.array([[0,1],[2,3]])

In [9]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [10]:
 #pinvx=np.linalg.pinv(array1)

### 矩阵乘法

In [11]:
array2.dot(array3)

array([[ 21,  21,  21],
       [ 84,  84,  84],
       [147, 147, 147]])

In [12]:
np.dot(array2,array3)

array([[ 21,  21,  21],
       [ 84,  84,  84],
       [147, 147, 147]])

## 广播运算

### 如果数组形状不匹配，数组会沿着维度为1的维度进行扩展

In [13]:
x1=np.ones((3,3))
x1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
x2=np.arange(3)
x2

array([0, 1, 2])

In [15]:
x1+x2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [16]:
x3=np.logspace(1,10,10,base=2).reshape(2,5)
x3

array([[   2.,    4.,    8.,   16.,   32.],
       [  64.,  128.,  256.,  512., 1024.]])

In [17]:
x4=np.array([[1,2,4,8,16]])
x4

array([[ 1,  2,  4,  8, 16]])

In [18]:
x3/x4

array([[ 2.,  2.,  2.,  2.,  2.],
       [64., 64., 64., 64., 64.]])

In [19]:
x5=np.arange(3).reshape(3,1)
x5

array([[0],
       [1],
       [2]])

In [20]:
x6=np.arange(3).reshape(1,3)
x6

array([[0, 1, 2]])

In [21]:
x5+x6

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## 库提供的tile方法

In [22]:
x7=np.tile(x6,(3,1))
x7[0][0]=2
print(x6)
print(x7)

[[0 1 2]]
[[2 1 2]
 [0 1 2]
 [0 1 2]]


## 比较运算和掩码

### 比较运算

In [23]:
x1=np.random.randint(100,size=(10,10))
x1

array([[63, 42, 47, 83, 58, 96, 66, 78, 23, 12],
       [48, 94, 72, 96, 80, 28, 40, 40, 47,  5],
       [69, 31, 70, 72, 80, 31, 81, 65, 85, 15],
       [35, 28, 62, 16, 95, 22, 76, 13, 10, 32],
       [59, 88,  5, 88, 20, 36, 59, 18, 53, 91],
       [98, 23, 74, 36, 80,  4,  4, 54, 79, 51],
       [24, 81, 46, 34, 16, 40,  6,  7, 78, 74],
       [48, 57,  3, 56, 15, 34, 85, 16, 12, 27],
       [76, 59,  1, 93, 79, 80, 86, 51, 20, 32],
       [13, 68, 44, 58, 29, 76, 73, 66, 17,  5]])

In [24]:
x1>50

array([[ True, False, False,  True,  True,  True,  True,  True, False,
        False],
       [False,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True, False,  True,  True,  True, False,  True,  True,  True,
        False],
       [False, False,  True, False,  True, False,  True, False, False,
        False],
       [ True,  True, False,  True, False, False,  True, False,  True,
         True],
       [ True, False,  True, False,  True, False, False,  True,  True,
         True],
       [False,  True, False, False, False, False, False, False,  True,
         True],
       [False,  True, False,  True, False, False,  True, False, False,
        False],
       [ True,  True, False,  True,  True,  True,  True,  True, False,
        False],
       [False,  True, False,  True, False,  True,  True,  True, False,
        False]])

### 布尔数组运算

In [25]:
np.sum(x1>50)

50

In [26]:
np.all(x1>0)

True

In [27]:
np.any(x2==10)

False

In [28]:
np.all(x1<50,axis=1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [29]:
(x1>10)&(x1<50)

array([[False,  True,  True, False, False, False, False, False,  True,
         True],
       [ True, False, False, False, False,  True,  True,  True,  True,
        False],
       [False,  True, False, False, False,  True, False, False, False,
         True],
       [ True,  True, False,  True, False,  True, False,  True, False,
         True],
       [False, False, False, False,  True,  True, False,  True, False,
        False],
       [False,  True, False,  True, False, False, False, False, False,
        False],
       [ True, False,  True,  True,  True,  True, False, False, False,
        False],
       [ True, False, False, False,  True,  True, False,  True,  True,
         True],
       [False, False, False, False, False, False, False, False,  True,
         True],
       [ True, False,  True, False,  True, False, False, False,  True,
        False]])

In [30]:
(x1>10)|(x1<8)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [31]:
np.count_nonzero(x1<=3)

2

## 布尔数组作为掩码

In [32]:
x1[x1>50]

array([63, 83, 58, 96, 66, 78, 94, 72, 96, 80, 69, 70, 72, 80, 81, 65, 85,
       62, 95, 76, 59, 88, 88, 59, 53, 91, 98, 74, 80, 54, 79, 51, 81, 78,
       74, 57, 56, 85, 76, 59, 93, 79, 80, 86, 51, 68, 58, 76, 73, 66])

# 花哨的索引

### 一维数组

In [33]:
x=np.random.randint(100,size=10)
x

array([27, 39, 65, 97,  6, 92, 34, 65, 98, 11])

In [34]:
index1=[2,4,6,8]
x[index1]

array([65,  6, 34, 98])

### 多维数组

In [35]:
x2=np.arange(12).reshape(3,4)
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
row=np.array([0,1,2])
col=np.array([1,3,0])
row2=[0,1,2]
col2=[1,3,0]
x2[row,col]
# print(x2[row2,col2])

array([1, 7, 8])

In [37]:
row[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [38]:
x2[row[:,np.newaxis],col]

array([[ 1,  3,  0],
       [ 5,  7,  4],
       [ 9, 11,  8]])

# Numpy通用函数

## 数值排序

In [62]:
x

array([27, 39, 65, 97,  6, 92, 34, 65, 98, 11])

In [61]:
np.sort(x)

array([ 6, 11, 27, 34, 39, 65, 65, 92, 97, 98])

In [41]:
np.argsort(x,axis=0)

array([4, 9, 0, 6, 1, 2, 7, 5, 3, 8], dtype=int64)

In [42]:
np.partition(x,3)

array([ 6, 11, 27, 34, 39, 65, 65, 97, 98, 92])

In [43]:
np.argpartition(x,3)

array([4, 9, 0, 6, 1, 7, 2, 3, 8, 5], dtype=int64)

In [44]:
x

array([27, 39, 65, 97,  6, 92, 34, 65, 98, 11])

## 获得排序索引

In [45]:
print(np.argsort(x))

[4 9 0 6 1 2 7 5 3 8]


## 最大最小值

In [46]:
print("max:",np.max(x))
print("min",np.min(x))
print("max_index:",np.argmax(x))
print("min_index",np.argmin(x))

max: 98
min 6
max_index: 8
min_index 4


## 数值求和,求积

In [47]:
x3=np.arange(1,6)
x3

array([1, 2, 3, 4, 5])

In [48]:
x.sum()

534

In [49]:
np.sum(x)

534

### 按行求和

In [50]:
np.sum(x2,axis=1)

array([ 6, 22, 38])

### 按列求和

In [51]:
np.sum(x2,axis=0)

array([12, 15, 18, 21])

## 求积

In [52]:
x

array([27, 39, 65, 97,  6, 92, 34, 65, 98, 11])

In [53]:
x.prod()

1771875168

In [54]:
np.prod(x)

1771875168

# 数据统计

## 中位数

In [55]:
np.median(x)

52.0

## 均值

In [56]:
np.mean(x)

53.4

## 方差

In [57]:
np.var(x)

1097.44

## 标准差

In [58]:
np.std(x)

33.12763197090912

## 百分位

In [59]:
np.percentile(x,q=10)

10.5

In [60]:
for percent in [0,25,50,75,100]:
    print(np.percentile(x,q=percent))


6.0
28.75
52.0
85.25
98.0
