# numpy库相关练习

## 为什么numpy库比较高效

### 1 由c语言编写，底层执行高效

### 2 单一类型存储

### 3 多线程

## numpy创建数组

In [2]:
import numpy as np

创建一个的浮点型数组一位数组

In [28]:
array1=np.array([1.5,2.4,3.9],dtype=float)
print(array1)

[1.5 2.4 3.9]


创建一个7*7的全一数组

In [29]:
array2=np.ones((7,7))
print(array2)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


创建一个值为6的6*6数组

In [30]:
array3=np.full((6,6),6)
print(array3)

[[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]


创建一个3*3的单位

In [31]:
array4=np.eye(3)
print(array4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


创建一个偶数列

In [32]:
array5=np.arange(0,18,2)
print(array5)

[ 0  2  4  6  8 10 12 14 16]


4等分2~8

In [46]:
array6=np.linspace(2,8,4)
print(array6)

[2. 4. 6. 8.]


创建一个等比数列

In [40]:
array7=np.logspace(0,9,10)
print(array7)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]


创建标准差为1，均值为0 的正态分布的10个随机数

In [42]:
array8=np.random.normal(0,1,10)
print(array8)

[-0.59596081  0.76484027  0.72004728 -0.28414614 -0.59065474  1.61820239
 -0.67540718  0.46517789  0.45689034 -0.11576924]


In [ ]:
np.random.seed(666)#可以指定种子 从而获得一样的值

In [3]:
np.random.randint(4,8,size=(2,5))

array([[4, 7, 5, 4, 4],
       [7, 5, 7, 6, 4]])

将array6随机排列

In [48]:
array9=np.random.permutation(array6)
print(array9)

[8. 2. 6. 4.]


改变序列array10=[5,11,3,7,9]的顺序

In [53]:
array10=[5,11,3,7,9]
np.random.shuffle(array10)
print(array10)

[3, 11, 7, 9, 5]


从array6中选出一个2*1的矩阵

In [56]:
array11=np.random.choice(array6,size=(2,1))
print(array11)

[[6.]
 [6.]]


In [7]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the ``normal`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int or tuple of ints, optional
    Output shape.  If t