# 练习

In [3]:
import numpy as np

In [4]:
x1=np.zeros((3,3))
x1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
x2=np.arange(0,10)
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x3=np.random.normal(0,1,size=(3,4))
x3

array([[-0.40137197,  2.58594457, -0.30191964, -0.06495161],
       [-1.43098219,  2.10174352,  1.32324937,  0.78543633],
       [ 0.58557294,  0.39174389,  0.82085425,  0.20261818]])

In [7]:
matrix=np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [8]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [9]:
array=np.random.randint(100,size=10)
array

array([31, 41, 69, 34, 26, 76, 96,  3, 21, 68])

In [10]:
array[array>30]

array([31, 41, 69, 34, 76, 96, 68])